'''
Project Euler Problem #45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
from math import sqrt
from math import ceil

def isTriangle(n):
    k=int(sqrt(n*2))
    return k*(k+1)==n*2

def isPentagonal(n):
    k=ceil(sqrt(n*2/3))
    return k*(3*k-1)==n*2

def isHexagonal(n):
    k=ceil(sqrt(n/2))
    return k*(2*k-1)==n

def genHexagonal(n):
    k=n
    while 1:
        yield 2*k*k-k
        k+=1

def find():
    h=144
    for i in genHexagonal(h):
        if isTriangle(i) and isPentagonal(i):
            print(i)
            return

find()
    
